require: rubocop-rspec

inherit_from: .rubocop_fixme.yml

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'build/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'config/**/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  ExcludedMethods: ['included']

Style/AsciiComments:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/ClassAndModuleChildren:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Layout/LineLength:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/system/**/*'
    - 'spec/views/**/*'
    - 'spec/config/initializers/**/*'

RSpec/LetSetup:
  Enabled: false

# # By default RSpec/MessageSpies has the following:
# #   Prefer have_received for setting message expectations. Setup form as a spy using allow or instance_spy.
# # The default assumes EnforcedStyle is 'have_received'. Most of our specs are 'receive'
RSpec/MessageSpies:
  Enabled: false


# FIXME: Disabled these new cops -rordway
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Lint/DeprecatedOpenSSLConstant:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false

# FIXME: Disabled these failing cops
Style/WordArray:
  Enabled: false
RSpec/EmptyLineAfterExample:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
