KIOSKS_SECRET_KEY_BASE: youmustchangethis
KIOSKS_DRUPAL_USERNAME: username
KIOSKS_DRUPAL_PASSWORD: password
KIOSKS_DRUPAL_HOST: localhost
KIOSKS_ROOMRES_USERNAME: username
KIOSKS_ROOMRES_PASSWORD: password
KIOSKS_ROOMRES_HOST: localhost
CAS_BASE_URL: 'https://example/cas'
CAS_VALIDATE_URL: 'https://example/cas/samlValidate'